#!/bin/bash
#堀内作成
#python インストール
#brew install python
#各ツールのアップデート
#pip install --upgrade setuptools
#pip install --upgrade pip
#pip install --upgrade gensim
#コマンドの使い方
#学習
#cat in|python train.py |python unescape.py 
#実行
#echo "魚 カサゴ 水族館"|python VECZO.py|python unescape.py

